### ISSUE TITLE
Intructions for setting up

### ISSUE THREAD

**Issue by ninrod** [noctuid/targets.el#1]
Hi @noctuid! So I've installed the package manually with:

```emacs-lisp
(use-package targets :load-path "lisp/noctuid/targets.el")
```

It is installed correctly because `C-h v` shows me the `targets-text-objects` variable.

But there is no seeking. for example `cib` will not seek forward. Do I have to setup up something else?

**Comment by noctuid** [comment]
Nothing is bound/created by default. Run `(targets-setup t)` to create and bind the text objects specified in `targets-text-objects`. Note that nothing is bound to `ib` currently. I'll add a lot more documentation once I've added all of the primary functionality and tests, but in the meantime feel free to ask any questions about the current functionality.

**Comment by ninrod** [comment]
@noctuid, just added that function and it is working fantastically. Will test more after Christmas. Awesome work!

**Comment by ninrod** [comment]
`(targets-setup t)` solved the issue.
