### ISSUE TITLE
don't require avy if user uses :remote-key nil

### ISSUE THREAD

**Issue by ninrod** [noctuid/targets.el#12]
Hi @noctuid, wouldn't it be best if target.el did not require avy when user specifies `:remote-key nil`? 

```elisp
(targets-setup t
                   :remote-key nil)
```

I was getting unclear error messages after updgrading target.el and found out that avy was required by targets even with `:remote-key nil`. As avy appeared later on my load order, it caught me offguard.

Another approach would be to leave the remote text object as an `opt in` feature. Not everybody uses avy and could cause issues. I, for one, do not use avy.

What do you think?

**Comment by ninrod** [comment]
For completeness, I had to do this: 

```elisp
(use-package avy :ensure t)
  (with-eval-after-load "avy"
    (use-package targets :load-path "lisp/noctuid/targets.el"
      :init
      (setq targets-separator-text-objects '())

      (add-to-list 'targets-separator-text-objects
                   '(pipe "|" nil separator))

      (setq targets-pair-text-objects
            '((paren "(" ")" pair :more-keys "b")
              (bracket "[" "]" pair :more-keys "r")
              (curly "{" "}" pair :more-keys "c")
              (angle "<" ">" pair)))
      :config

      (targets-setup t
                     :inside-key nil
                     :around-key nil
                     :remote-key nil)))
```

**Comment by ninrod** [comment]
Perhaps this will only be an issue for manual installation. When targets.el is on melpa this will be automatically solved because the package manager will download avy as a dep?

**Comment by noctuid** [comment]
Yes, avy will be installed once it's on melpa. I'd rather keep it as a dependency, so it will be there if needed. I'll defer loading avy until the remote text objects are actually used though. I think that's a good idea even if the remote text objects will always be used.
