### ISSUE TITLE
seeking `ci(` is broken on master

### ISSUE THREAD

**Issue by ninrod** [noctuid/targets.el#18]
but it works on commit 387fd6c.

to reproduce: 

just type this on scratch buffer (cursor on [])

```txt
[b]lah blah blah (foo bar buz)
```

now type `ci(`

expected: `ci(` should seek

actual: `ci(` does not seek.

**Comment by noctuid** [comment]
I cannot reproduce this problem. Did it break for you after fd707aa?

**Comment by ninrod** [comment]
well, I also can't reproduce it anymore. maybe some interplay with another package I was trying. 

sorry @noctuid.
