### ISSUE TITLE
option to include "alias" to some text objects

### ISSUE THREAD

**Issue by ninrod** [noctuid/targets.el#2]
Hi @noctuid, and thank you for this awesome package.

I use `cib` instead of `ci(`. I find it a bit faster and more convenient (I don't need to press shift). 

`ci(` is working fantastically in `targets.el`. I'd like to create like an alias where `cib` would be equivalent to typing `ci(`.  Similarly, `cir` would be equivalent to `ci[` and so on and so forth. 

Is there a way to do that?

**Comment by noctuid** [comment]
Yes, for example you can change `(paren "(" ")" pair)` in `targets-text-objects` to `(paren "(" ")" pair :more-keys "b")`.

**Comment by ninrod** [comment]
ok, this is working beautifully with the last commit ( which split the text-objects)

```elisp
(use-package targets :load-path "lisp/noctuid/targets.el"
    :init
    (setq targets-pair-text-objects
          '((paren "(" ")" pair :more-keys "b")
            (bracket "[" "]" pair :more-keys "r")
            (curly "{" "}" pair :more-keys "c")
            (angle "<" ">" pair)))

    :config
    (targets-setup t)
    )
```
