### ISSUE TITLE
`non-prefix-key` warning for `I` and `A` when binding visual state

### ISSUE THREAD

**Issue by JJPandari** [noctuid/targets.el#30]
when I do 

```lisp
(targets-define-composite-to pair-delimiter
  (("(" ")" pair)
   ("[" "]" pair)
   ("{" "}" pair)
   ("<" ">" pair))
  :bind t
  :next-key "N"
  :last-key "L"
  :remote-key nil
  :keys "d")
```

I have the `binding to non-prefix key "I"` warning, because `I` and `A` are already bound in visual state. Unbinding them fixes this:

```lisp
(general-define-key
 :keymaps 'evil-visual-state-map
 "I" nil
 "A" nil)
```

Is it related to my other config or this happens for everyone? If this happens to everyone, should we do the above unbinding for the user silently?

**Comment by noctuid** [comment]
Targets has to handle I and A specially, and you'll need to run `targets-setup`. Try customizing `targets-composite-text-objects` and then running targets-setup.
