### ISSUE TITLE
what is the cleanest way to customize single elements in the targets-pair-text-objects list?

### ISSUE THREAD

**Issue by ninrod** [noctuid/targets.el#8]
hi @noctuid. I'm using this package 24/7 to great success. It is awesome already. I don't miss a thing from [wellle/targets.vim](http://github.com/wellle/targets.vim)

I like to use `b` instead of `(` for the round bracket text object. So I've setup my targets.el like so:

```elisp
(use-package targets :load-path "lisp/noctuid/targets.el"
    :init
    (setq targets-separator-text-objects '())

    (add-to-list 'targets-separator-text-objects
                 '(pipe "|" nil separator))

    (setq targets-pair-text-objects
          '((paren "(" ")" pair :more-keys "b")
            (bracket "[" "]" pair :more-keys "r")
            (curly "{" "}" pair :more-keys "c")
            (angle "<" ">" pair)))
    :config
    (targets-setup t))
```

But I'm nervous that new text objects could be added/removed. Is there a cleaner way to alias the `(` text object than what I'm using? 

Thanks!

**Comment by noctuid** [comment]
The shortest way might be to destructively append to the list. Something like this would probably cleaner/more general:

```elisp
(defun my-targets-replace-to (name new-to)
  (setq targets-text-objects
        (cons new-to
              (cl-remove-if `(lambda (x) (eq (car x) ',name))
                            targets-text-objects))))

(my-targets-replace-to 'paren
                       '(paren "(" ")" pair :more-keys "b"))
```

I could maybe add something like this function to the package to simplify things.

**Comment by ninrod** [comment]
@noctuid, maybe the user could provide like a list with option pairs like:

```elisp
(setq alias-pair '(("paren" . "b")))
(add-to-list alias-pair '("bracket" . "r"))
```

And then the package could do the proper matching

What you think?

**Comment by noctuid** [comment]
I'd rather have something that works in general instead of just for `:more-keys`. How about something like a `targets-user-text-objects` with the same format as `targets-text-objects`? Text objects from `targets-user-text-objects` would take precedence for duplicate names.

**Comment by ninrod** [comment]
@noctuid yes, that'd be awesome. 

By the way I want to help you to develop the package, but I'm an elisp total beginner. Maybe we can have like beginner issues up for grabs? I could write the solution for them and then after I learn enough elisp I could help you with intermediate and harder ones. 

Do you think that implementing the `targets-user-text-objects` is a beginner friendly one, for example? 

What you think?

**Comment by noctuid** [comment]
Yeah, this would be a good feature to start with. If you want to try it, you could make a pull request with the following changes:

1. Add a new variable called `targets-user-text-objects` defined under `targets-text-objects`
2. Replace `targets-text-objects` in `targets-setup` with the necessary code to combine `targets-text-objects` and `targets-user-text-objects`. The result should only have the text objects from `targets-user-text-objects` for any name matches.

There's a pretty simple way to do this, but I don't know if you'd rather find out what functions to use on your own, so I'll leave it at that. Let me know if you want any more information.

**Comment by ninrod** [comment]
Ok then, this is my first mission, :face_with_head_bandage:

**Comment by ninrod** [comment]
Ok. I think that if I solve [this](https://github.com/ninrod/merge-custom-plist/blob/master/merge.el), I'll be able to write the pull.

**Comment by noctuid** [comment]
Yes, though instead of adding a dependency on dash, please use cl-lib since I already have it as a dependency (`cl-union` is the equivalent of `-union`).

**Comment by ninrod** [comment]
Sure thing.

**Comment by ninrod** [comment]
@noctuid, why do you prefer `cl-lib` over `dash`? Just curious/want to learn more.

**Comment by noctuid** [comment]
I don't necessarily prefer `cl-lib`; `dash` has a lot of excellent functionality not present in `cl-lib`, but the reverse is also true. There is overlap between the two libraries, but in this package (and others I've written) I'm using `cl-lib` primarily because it adds a lot of basic functionality that emacs lisp doesn't have. For example, common lisp's `defun` supports keyword arguments and specifying default values for optional arguments. It also implicitly wraps the function in a block, so that you can prematurely return from it with `return-from`. Emacs lisp's `defun` does not support any of these features, but there is `cl-defun` which does. As another example, emacs lisp doesn't have a `case` macro by default, but `cl-lib` provides one. If I needed to do more complicated list processing, I would probably use dash for that.

**Comment by ninrod** [comment]
Ok, so I think I've managed to write the pull request: #13
