### ISSUE TITLE
targets.el totally hyjacks the `I` bind in evil's visual block state

### ISSUE THREAD

**Issue by ninrod** [noctuid/targets.el#9]
@noctuid I just hit a major bug brought by targets.el: the hijacking for the `I` keybind in visual block state. 

__steps to reproduce__: 

just type like 3 lines of text. cursor is [|]
```txt
[l]ine1
line2
line3
```

hit `C-v` and draw a line block like this:

just type like 3 lines of text. cursor is [|]
```txt
[l]ine1
[l]ine2
[l]ine3
```

Now you want to append spaces at the beginning of the lines. So you have to hit `I`. Targets hijacks `I`. It even opens up which key to show possible binds:

![image](https://cloud.githubusercontent.com/assets/8352747/22110054/7dcd1920-de41-11e6-9c58-e512c376f708.png)

**Comment by noctuid** [comment]
This isn't really a bug, or at least this is expected when you rebind `I` in visual state.  I haven't yet decided the best way to handle this. For now, I'd just recommend rebinding `I`and `A` in visual state to `evil-insert` and `evil-append` after running `targets-setup`. 

I want to see whether `I` and `A` are used in visual char/line mode for targets.vim. I could maybe have an alternate binding used just for visual block mode and bind `I` to a menu-item that chooses the correct definition based on the type of visual state.

**Comment by ninrod** [comment]
Ok but why to you need to bind `I` and `A`? What are you binding them to?

**Comment by noctuid** [comment]
They are used for the "inside" and "around" text objects.

**Comment by ninrod** [comment]
wait. I never used them. what is the difference between lower case `i` and `a` and uppercase `I` and `A`? 

I always use `vi*` to great effect. I never used `vI*`. What gives?

**Comment by noctuid** [comment]
They are from targets.vim. See [this section](https://github.com/noctuid/targets.el#i-a-i-a-l-n-r) from the readme for a brief description.

**Comment by ninrod** [comment]
Jesus I did not even know that that existed.

**Comment by ninrod** [comment]
@noctuid, why doesn't targets.vim hijacks `I` and `A` binds in vim in visual block mode? Does this happen in evil because there is really no visual-block state? Like couldn't you only hijack `I` and `A` in visual state but not in visual block state? (Just trying to figure this out).

**Comment by noctuid** [comment]
I don't know how targets.vim implements them, but in evil there is not a separate state/keymap for visual block. It looks like it is possible to handle this with a menu-item like I thought though:

```elisp
(define-key evil-visual-state-map "I"
  '(menu-item "" nil
              :filter (lambda (&optional _)
                        (if (eq (evil-visual-type) 'block)
                            #'evil-insert
                          targets-inside-text-objects-map))))
```

I need to decide how to handle things if different keys are specified instead of `I` and `A`, but I'll add this fix when I get the chance.

**Comment by ninrod** [comment]
Oh, right, all makes sense now.

**Comment by noctuid** [comment]
The issue should be fixed now. If you don't want to use the inside and around text objects, you can use this:
```elisp
(targets-setup t :inside-key nil :around-key nil)
```

As a heads up, I've added remote text objects now, so if you update, you'll want to change `:remote-key` to something else since you are already using "r".
```elisp
;; don't bind remote text objects
(targets-setup t :remote-key nil)
```

**Comment by ninrod** [comment]
@noctuid that's awesome. What are exactly the `remote` text objects? 

edit: oh, I see you left a note on the readme. integration with avy. cool.
